import { VoiceOption, PresetScene, AudioTagOption } from '../types';

export const GEMINI_VOICES: VoiceOption[] = [
  {
    id: 'Zephyr',
    name: 'Zephyr',
    gender: 'female',
    description: 'Tươi sáng — Giọng nữ rạng rỡ, truyền cảm, tự nhiên',
    bestFor: 'Hướng dẫn nhanh, Vlog cá nhân, CSKH, Quảng cáo',
    avatarColor: 'from-amber-400 to-orange-500',
    sampleText: 'Chỉ với vài thao tác đơn giản, bạn đã có thể sáng tạo nên nội dung âm thanh tuyệt vời.',
  },
  {
    id: 'Puck',
    name: 'Puck',
    gender: 'male',
    description: 'Rộn ràng — Giọng nam vui tươi, năng động, tươi trẻ',
    bestFor: 'Quảng cáo, Review sản phẩm, Video TikTok / Reels, Game',
    avatarColor: 'from-blue-500 to-indigo-600',
    sampleText: 'Chào mừng các bạn đến với ứng dụng hôm nay! Cùng trải nghiệm tính năng tuyệt vời này nhé.',
  },
  {
    id: 'Charon',
    name: 'Charon',
    gender: 'male',
    description: 'Cung cấp nhiều thông tin — Giọng nam trầm ấm, chi tiết, chuyên sâu',
    bestFor: 'Phim tài liệu, Bài giảng khoa học, Đọc tin tức, Truyện đêm',
    avatarColor: 'from-purple-600 to-slate-900',
    sampleText: 'Hệ thống vũ trụ chứa đựng hàng tỷ thiên hà với những bí ẩn chưa từng được khám phá.',
  },
  {
    id: 'Kore',
    name: 'Kore',
    gender: 'female',
    description: 'Firm — Giọng nữ vững chắc, dứt khoát, chuẩn mực',
    bestFor: 'Sách nói, Podcast, Thuyết minh doanh nghiệp, Trợ lý AI',
    avatarColor: 'from-pink-500 to-rose-600',
    sampleText: 'Xin chào! Tôi là Kore. Rất vui được đồng hành cùng bạn trong trải nghiệm âm thanh hôm nay.',
  },
  {
    id: 'Fenrir',
    name: 'Fenrir',
    gender: 'male',
    description: 'Dễ kích động — Giọng nam bùng nổ, sôi nổi, kịch tính',
    bestFor: 'Bình luận thể thao, Trailer hành động, Sự kiện bùng nổ',
    avatarColor: 'from-red-600 to-orange-600',
    sampleText: 'Khoảnh khắc lịch sử đã đến! Một cú dứt điểm không thể tuyệt vời hơn!',
  },
  {
    id: 'Leda',
    name: 'Leda',
    gender: 'female',
    description: 'Trẻ trung — Giọng nữ trong trẻo, tươi mới, thanh thanh',
    bestFor: 'Sách nói thiếu nhi, Video xu hướng, Giới thiệu sản phẩm mới',
    avatarColor: 'from-cyan-400 to-blue-500',
    sampleText: 'Mỗi ngày mới là một khởi đầu tuyệt vời tràn đầy niềm vui và cơ hội.',
  },
  {
    id: 'Orus',
    name: 'Orus',
    gender: 'male',
    description: 'Firm — Giọng nam dứt khoát, dũng mãnh, đầy tự tin',
    bestFor: 'Keynote bài phát biểu, Thông điệp lãnh đạo, Bản tin chính luận',
    avatarColor: 'from-emerald-600 to-teal-800',
    sampleText: 'Chúng ta kiên định hướng tới mục tiêu và mang đến những giá trị đột phá nhất.',
  },
  {
    id: 'Aoede',
    name: 'Aoede',
    gender: 'female',
    description: 'Breezy — Giọng nữ thong thả, tự do, thơ mộng',
    bestFor: 'Thơ ca, Audio thư giãn, Thiền định, Podcast nhẹ nhàng',
    avatarColor: 'from-violet-400 to-purple-600',
    sampleText: 'Thả lỏng tâm trí và lắng nghe tiếng gió rì rào trong buổi chiều thu bình yên.',
  },
  {
    id: 'Callirrhoe',
    name: 'Callirrhoe',
    gender: 'female',
    description: 'Dễ chịu — Giọng nữ êm ái, thân thiện, tạo sự thoải mái',
    bestFor: 'Hướng dẫn sức khỏe, Chăm sóc khách hàng, Trợ lý ảo',
    avatarColor: 'from-rose-400 to-pink-500',
    sampleText: 'Cảm ơn bạn đã ghé thăm. Tôi luôn sẵn sàng hỗ trợ bạn bất cứ lúc nào.',
  },
  {
    id: 'Autonoe',
    name: 'Autonoe',
    gender: 'female',
    description: 'Sáng — Giọng nữ rạng rỡ, vang sáng, cuốn hút',
    bestFor: 'Show truyền hình, Giới thiệu sự kiện, Bản tin thời trang',
    avatarColor: 'from-yellow-400 to-amber-500',
    sampleText: 'Chào mừng quý vị khán giả đến với chương trình âm nhạc đặc sắc ngày hôm nay!',
  },
  {
    id: 'Enceladus',
    name: 'Enceladus',
    gender: 'male',
    description: 'Breathy — Giọng nam thì thầm, sâu lắng, nhiều nhịp thở',
    bestFor: 'Truyện trinh thám, Kinh dị, Thiền định, Kể chuyện tâm tình',
    avatarColor: 'from-sky-500 to-indigo-600',
    sampleText: 'Im lặng... Lắng nghe từng bước chân khẽ vang lên trong màn đêm huyền bí.',
  },
  {
    id: 'Iapetus',
    name: 'Iapetus',
    gender: 'male',
    description: 'Rõ ràng — Giọng nam rành mạch, phát âm chuẩn xác',
    bestFor: 'Bài giảng trực tuyến, Từ điển phát âm, Thuyết minh giáo dục',
    avatarColor: 'from-slate-600 to-blue-800',
    sampleText: 'Mỗi khái niệm khoa học đều đòi hỏi sự chuẩn xác và thấu hiểu tận gốc rễ.',
  },
  {
    id: 'Umbriel',
    name: 'Umbriel',
    gender: 'male',
    description: 'Dễ tính — Giọng nam thoải mái, mộc mạc, tự nhiên',
    bestFor: 'Vlog trải nghiệm cuộc sống, Trò chuyện hàng ngày, Podcast casual',
    avatarColor: 'from-teal-500 to-cyan-600',
    sampleText: 'Cứ tự nhiên thưởng thức ly cà phê ấm và trò chuyện cùng nhau nhé.',
  },
  {
    id: 'Algieba',
    name: 'Algieba',
    gender: 'male',
    description: 'Làm mịn — Giọng nam mượt mà, dịu nhẹ, cân bằng',
    bestFor: 'Sách nói văn học, Radio đêm, Kể chuyện nhẹ nhàng',
    avatarColor: 'from-indigo-500 to-purple-700',
    sampleText: 'Dòng sông êm đềm trôi qua những cánh đồng xanh ngát trong ánh chiều tà.',
  },
  {
    id: 'Despina',
    name: 'Despina',
    gender: 'female',
    description: 'Smooth — Giọng nữ mượt mà, truyền cảm, duyên dáng',
    bestFor: 'Quảng cáo thương hiệu cao cấp, Spa thư giãn, Đọc tiểu thuyết',
    avatarColor: 'from-fuchsia-400 to-rose-500',
    sampleText: 'Trải nghiệm sự tinh tế và đẳng cấp trong từng đường nét âm thanh đỉnh cao.',
  },
  {
    id: 'Erinome',
    name: 'Erinome',
    gender: 'female',
    description: 'Clear — Giọng nữ rõ ràng, sắc nét, trong trẻo',
    bestFor: 'Thông báo sân bay / nhà ga, Hướng dẫn ứng dụng, Podcast học thuật',
    avatarColor: 'from-emerald-400 to-green-600',
    sampleText: 'Xin lưu ý: Chuyến bay tiếp theo sẽ bắt đầu làm thủ tục tại cửa số 5.',
  },
  {
    id: 'Algenib',
    name: 'Algenib',
    gender: 'male',
    description: 'Khàn — Giọng nam trầm khàn, phong trần, đầy cá tính',
    bestFor: 'Kể chuyện đời thực, Phim hành động, Nhạc kịch, Rock ballad',
    avatarColor: 'from-orange-700 to-stone-900',
    sampleText: 'Con đường dài phía trước còn nhiều thử thách, nhưng tôi chưa bao giờ bỏ cuộc.',
  },
  {
    id: 'Rasalgethi',
    name: 'Rasalgethi',
    gender: 'male',
    description: 'Cung cấp nhiều thông tin — Giọng nam trí tuệ, đĩnh đạc, phân tích',
    bestFor: 'Bản tin tài chính, Phân tích kinh tế, Thuyết minh bảo tàng',
    avatarColor: 'from-blue-700 to-slate-900',
    sampleText: 'Báo cáo chỉ ra xu hướng phát triển bền vững trong ngành năng lượng tái tạo.',
  },
  {
    id: 'Laomedeia',
    name: 'Laomedeia',
    gender: 'female',
    description: 'Rộn ràng — Giọng nữ nhộn nhịp, tươi vui, nhiều năng lượng',
    bestFor: 'Gameshow, Trẻ em, Sự kiện lễ hội, Quảng cáo nhộn nhịp',
    avatarColor: 'from-pink-400 to-purple-500',
    sampleText: 'Xin chào cả nhà! Hôm nay chúng ta sẽ cùng tham gia trò chơi cực kỳ thú vị!',
  },
  {
    id: 'Achernar',
    name: 'Achernar',
    gender: 'female',
    description: 'Dịu êm — Giọng nữ êm ái, ngọt ngào, ấm áp',
    bestFor: 'Hát ru, Truyện ngủ cho bé, Thiền hướng dẫn, Audio lãng mạn',
    avatarColor: 'from-purple-400 to-indigo-600',
    sampleText: 'Chúc em ngủ ngon và có những giấc mơ thật đẹp trong đêm nay.',
  },
  {
    id: 'Alnilam',
    name: 'Alnilam',
    gender: 'male',
    description: 'Firm — Giọng nam chững chạc, uy nghiêm, dứt khoát',
    bestFor: 'Thuyết minh quân sự, Bản tin an ninh, Phim lịch sử',
    avatarColor: 'from-cyan-600 to-blue-800',
    sampleText: 'Kỷ luật và tinh thần trách nhiệm là nền tảng vững chắc nhất của sức mạnh.',
  },
  {
    id: 'Schedar',
    name: 'Schedar',
    gender: 'male',
    description: 'Even — Giọng nam điềm tĩnh, nhịp nhàng, trung tính',
    bestFor: 'Sách nói phi hư cấu, Hướng dẫn thao tác máy tính, Trợ lý giọng nói',
    avatarColor: 'from-slate-500 to-zinc-700',
    sampleText: 'Tiếp tục theo dõi các bước trên màn hình để hoàn tất quá trình cài đặt.',
  },
  {
    id: 'Gacrux',
    name: 'Gacrux',
    gender: 'male',
    description: 'Dành cho người lớn — Giọng nam trưởng thành, đĩnh đạc, chiêm nghiệm',
    bestFor: 'Hồi ký, Đọc sách triết học, Phim tài liệu lịch sử cổ đại',
    avatarColor: 'from-amber-800 to-stone-900',
    sampleText: 'Nhìn lại chặng đường đã qua, những bài học quý giá nhất luôn đến từ sự kiên trì.',
  },
  {
    id: 'Pulcherrima',
    name: 'Pulcherrima',
    gender: 'female',
    description: 'Chuyển tiếp — Giọng nữ biến hóa linh hoạt, đa cảm xúc',
    bestFor: 'Kịch phát thanh, Truyện nhiều vai, Diễn xuất giọng nói',
    avatarColor: 'from-rose-500 to-amber-600',
    sampleText: 'Từ ngạc nhiên chuyển sang vỡ òa hạnh phúc, cô ấy mỉm cười rạng rỡ.',
  },
  {
    id: 'Achird',
    name: 'Achird',
    gender: 'male',
    description: 'Thân thiện — Giọng nam ấm áp, gần gũi, mở lòng',
    bestFor: 'Chia sẻ kinh nghiệm, Tâm sự tuổi trẻ, Tư vấn cộng đồng',
    avatarColor: 'from-lime-500 to-emerald-600',
    sampleText: 'Mình luôn tin rằng mọi nỗ lực của bạn ngày hôm nay sẽ được đền đáp xứng đáng.',
  },
  {
    id: 'Zubenelgenubi',
    name: 'Zubenelgenubi',
    gender: 'male',
    description: 'Bình thường — Giọng nam mộc mạc, bình dị, tự nhiên',
    bestFor: 'Hội thoại đời thường, Phỏng vấn thực địa, Thu âm tự nhiên',
    avatarColor: 'from-zinc-500 to-slate-700',
    sampleText: 'Hôm nay thời tiết khá đẹp, rất thích hợp cho một chuyến dã ngoại ngoài trời.',
  },
  {
    id: 'Vindemiatrix',
    name: 'Vindemiatrix',
    gender: 'female',
    description: 'Dịu dàng — Giọng nữ thướt tha, uyển chuyển, nhẹ nhàng',
    bestFor: 'Quảng cáo trà / hoa tươi, Giới thiệu văn hóa dân gian, Đọc thơ',
    avatarColor: 'from-teal-400 to-emerald-600',
    sampleText: 'Hương thơm dịu nhẹ của tách trà sớm mang lại cảm giác thư thái lạ kỳ.',
  },
  {
    id: 'Sadachbia',
    name: 'Sadachbia',
    gender: 'female',
    description: 'Lively — Giọng nữ sinh động, tràn đầy năng lượng tươi vui',
    bestFor: 'Video thời trang thanh thiếu niên, TikTok, Trò chơi điện tử',
    avatarColor: 'from-yellow-400 to-orange-500',
    sampleText: 'Cùng khám phá ngay bộ sưu tập mới nhất với hàng ngàn ưu đãi hấp dẫn!',
  },
  {
    id: 'Sadaltager',
    name: 'Sadaltager',
    gender: 'male',
    description: 'Hiểu biết — Giọng nam thông tuệ, tự tin, chuyên gia',
    bestFor: 'Podcast công nghệ, Thuyết trình dự án, Bài giảng đại học',
    avatarColor: 'from-blue-600 to-indigo-800',
    sampleText: 'Phân tích dữ liệu thực tế giúp chúng ta đưa ra những quyết định tối ưu.',
  },
  {
    id: 'Sulafat',
    name: 'Sulafat',
    gender: 'female',
    description: 'Ấm — Giọng nữ nồng ấm, giàu cảm xúc, truyền cảm sâu sắc',
    bestFor: 'Truyện cảm động, Thông điệp yêu thương, Audio gia đình',
    avatarColor: 'from-orange-500 to-rose-600',
    sampleText: 'Gia đình luôn là nơi bình yên nhất đón ta trở về sau những bão giông.',
  },
];

export const GEMINI_AUDIO_TAGS: AudioTagOption[] = [
  { tag: '[whispering]', label: 'Thì thầm', description: 'Nói nhỏ nhẹ, thì thầm bí mật', category: 'expression' },
  { tag: '[shouting]', label: 'Hô to', description: 'Nói lớn giọng, hô vang hoặc hét', category: 'expression' },
  { tag: '[sighs]', label: 'Thở dài', description: 'Tiếng thở dài thướt tha, buồn u uất', category: 'expression' },
  { tag: '[gasping]', label: 'Thở dốc', description: 'Hít một hơi sâu ngạc nhiên hoặc hoảng hốt', category: 'expression' },
  { tag: '[giggling]', label: 'Cười khúc khích', description: 'Tiếng cười nhỏ tinh nghịch', category: 'expression' },
  { tag: '[laughing]', label: 'Cười lớn', description: 'Tiếng cười sảng khoái', category: 'expression' },
  { tag: '[clears throat]', label: 'Thắng giọng', description: 'E hèm, dọn giọng trước khi phát biểu', category: 'expression' },
  { tag: '[excited]', label: 'Hào hứng', description: 'Giọng nói vui tươi, tràn đầy năng lượng', category: 'emotion' },
  { tag: '[sad]', label: 'Trầm buồn', description: 'Giọng chùng xuống, ưu tư', category: 'emotion' },
  { tag: '[confident]', label: 'Tự tin', description: 'Dứt khoát, dũng mãnh, đầy thuyết phục', category: 'emotion' },
  { tag: '[fast]', label: 'Đọc nhanh', description: 'Tăng nhịp điệu dồn dập', category: 'pace' },
  { tag: '[slow]', label: 'Đọc chậm', description: 'Nhịp điệu thong thả, từ tốn', category: 'pace' },
  { tag: '[pause 0.5s]', label: 'Tạm dừng 0.5s', description: 'Khoảng lặng ngắt nhịp nhẹ', category: 'pause' },
  { tag: '[pause 1.0s]', label: 'Tạm dừng 1s', description: 'Khoảng lặng sâu tạo điểm nhấn', category: 'pause' },
];

export const DEFAULT_PRESET_SCENES: PresetScene[] = [
  {
    id: 'preset-review-tech',
    title: 'Review Công Nghệ TikTok/Reels',
    description: 'Giọng nam Puck năng động + phong cách hào hứng',
    category: 'Quảng Cáo & Intro',
    mode: 'single',
    voiceName: 'Puck',
    speed: 1.1,
    pitch: 0,
    style: 'cheerful',
    promptConfig: {
      sceneContext: 'Phòng thu video review sống động',
      directorsNotes: 'Năng lượng cao, nhịp điệu dồn dập, nhấn mạnh tính năng nổi bật',
    },
    singleText: '[excited] Cực sốc! Đây là chiếc tai nghe chống ồn tốt nhất năm 2026 mà bạn không thể bỏ qua. Âm bass lực, pin dùng cả tuần!',
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'preset-night-story',
    title: 'Truyện Đêm Muộn Sâu Lắng',
    description: 'Giọng nam trầm Charon kể chuyện trôi chảy',
    category: 'Sách Nói & Kể Chuyện',
    mode: 'single',
    voiceName: 'Charon',
    speed: 0.9,
    pitch: -2,
    style: 'storytelling',
    promptConfig: {
      audioProfile: 'Người kể chuyện đêm muộn ấm áp',
      sceneContext: 'Đêm khuya tĩnh mịch',
      directorsNotes: 'Đọc thong thả [slow], giọng thì thầm nhẹ ở cuối câu [whispering]',
    },
    singleText: 'Thời gian trôi đi âm thầm như dòng sông chảy về biển lớn. [sighs] Giữa thành phố lên đèn, có những ký ức chưa bao giờ phai nhạt.',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'preset-podcast-interview',
    title: 'Phỏng Vấn Podcast 2 Người',
    description: 'Hội thoại đối đáp tự nhiên giữa Nam và Nữ',
    category: 'Podcast & Talkshow',
    mode: 'multi',
    speed: 1.0,
    pitch: 0,
    style: 'natural',
    speakers: [
      { id: 'spk-1', name: 'MC Hoàng', voiceName: 'Puck', style: 'natural', audioProfile: 'Nam MC tự tin, dí dỏm' },
      { id: 'spk-2', name: 'Chuyên gia Linh', voiceName: 'Kore', style: 'authoritative', audioProfile: 'Nữ chuyên gia sâu sắc, uyên bác' },
    ],
    dialogueLines: [
      { id: 'line-1', speakerId: 'spk-1', text: '[excited] Chào chị Linh! Chị đánh giá thế nào về làn sóng chuyển đổi số hiện nay?' },
      { id: 'line-2', speakerId: 'spk-2', text: 'Đây là thời điểm bứt phá [pause 0.5s]. Doanh nghiệp nào làm chủ công nghệ sẽ nắm thế chủ động.' },
      { id: 'line-3', speakerId: 'spk-1', text: '[giggling] Cảm ơn những chia sẻ rất thực tế của chị!' },
    ],
    createdAt: Date.now(),
  },
];

